### ISSUE TITLE
Add command line parameter to customize launch command

### ISSUE THREAD

**Issue by Lucide** [lemasato/Steam-Account-Switcher#1]
A command line parameter to customize the command (and parameters) ran after the accounts switcheroo.
Useful if someone needs to launch Steam through other programs.

I was thinking to write and propose the feature myself, but It seems that Autohotkey's syntax and logic are a bit less intuitive than I thought.

**Comment by lemasato** [comment]
Just wondering.
Soo what you exactly need is this tool to launch a custom program (+params) instead of Steam, right?

Why not just make it run a .lnk file instead? It would have your params already.

**Comment by Lucide** [comment]
A custom path set from command line can be account-specific.
For example, I have my primary account, which I use normally, and a secondary one, which has to be used with Steam ran through a wrapper.
To do this, two shortcuts to your tool are made: the "primary" one doesn't use the /path parameter, the "secondary" one does.
I've closed the issue because I've eventually read enough ahk documentation to write the small edit myself, I've sent it to you as a pull request
If you feel to, you can check it out :-)

**Comment by lemasato** [comment]
In this case, assuming that you're using the /Account param, how about

First account:
"Steam Account Switcher.exe" /Account=myAccount
Sets the account to myAccount and uses the normal Steam location.

Second Account:
"Steam Account Switcher.exe" /Account=mySecondAccount /SteamExe="Path/To/Your/Wrapper/Shortcut.lnk"
Sets the account to mySecondAccount and launches the .lnk file instead of Steam. This lnk file would point to your Steam Wrapper thing, and would already contain the params that it requires.

**Comment by Lucide** [comment]
That's the idea, but I don't get why parameter should be treated separately. I mean, they're simply a string of text after the exe path, you can simply shove the whole string into ahk's `Run`. If you decide to implement the SteamExe feature, eventual  parameters should just came along implicitly.

**Comment by lemasato** [comment]
Hi, sorry I kind of forgot about this. I just pushed something similar. It'll be available in next update. The /SteamPath parameter can work with:
- Only the Steam folder. In this case, the executable will be the default Steam.exe
eg: `/SteamPath="C:\Program Files (x86)\Steam"`
- The full exe path, in case you want to use a specific executable
eg: `/SteamPath="C:\Program Files (x86)\Steam\Steam.exe"`
It also works with parameters.
eg: `/SteamPath="C:\Program Files (x86)\Steam\Steam.exe -dosomething -someparameter"`

**Comment by Lucide** [comment]
Hi, I've just came back from my patched fork, now that the feature made it to release. There's a small issue tho: the app can't start executables that aren't named "Steam.exe".
I know no ahk, but it seems that e59916a splits exclusively for "Steam.exe". the result is a `foo\bar/.` command that opens the file explorer instead!

**Comment by lemasato** [comment]
What do you want to use this for?
Normally we start steam with the -shutdown parameter to make it close itself (in case it was currently running).
This allows making sure we are closing the right instance of Steam in case the user is running multiple instances of it.
I suspect this wouldn't work with other custom executables, and you would have to close Steam manually before starting Steam Account Switcher.

**Comment by Lucide** [comment]
I agree the app shouldn't interact with custom executables at all.
Everything it does already (like the automatic steam shutdown) should be kept as-is.
The context here is to launch a wrapper/helper of some sort that itself launches Steam. The wrapper's lifecycle management is outside of this app's job.

**Comment by lemasato** [comment]
Could you try with the branch as it is now and confirm that everything works as it should with your wrapper?

**Comment by Lucide** [comment]
Currently the custom executable is launched correctly, but the "auto shutdown" feature breaks when using it.

**Comment by lemasato** [comment]
Yeah that's what I expected would happen.
Normally the /SteamPath param should only be used to specify which Steam installation should be used.
In your case I guess a new parameter /UseDefaultSteamFolderForShutdown (?) so that the shutdown is done on the default Steam installation path and not the provided path.

**Comment by Lucide** [comment]
Or perhaps it could be called "LaunchCommand", to highlight that it won't be treated as Steam.
I don't even know if renaming "Steam.exe" itself is actually doable. I expect that to break something.

**Comment by lemasato** [comment]
LaunchCommand? Sorry I'm getting confused, what would it do?
We're trying to find a solution to automatically close Steam if the given path is an external executable (wrapper). In my opinion killing any Steam.exe process is a bad idea considering Steam itself offers the -shutdown parameter. So my solution was to simply do the -shutdown on the default Steam location if SAS detect the corresponding param.

**Comment by Lucide** [comment]
I was suggesting that `/SteamPath` should be used to define the Steam executable (the "file mode" is probably not needed, because renaming Steam.exe could have unforeseeable consequences).

But since the beginning, this issue was not about customizing the steam path/executable name. It was about customizing the launch command, and only that. The `/SteamPath` parameter is welcome, but it's more advanced as it defines a different Steam executable, and thus needs to be "corrected" with this new `/UseDefaultSteamFolderForShutdown`.

Now that we have it I would disable `/SteamPath`'s "file mode", it makes little sense, add a `/LaunchCommand` or whatever, and call it a day.\
The fancy steam integrated features would use the Steam executable defined in `/SteamPath`, `/LaunchCommand` would be then used as the launch command and as the launch command only.

Either way, the feature is here.

**Comment by lemasato** [comment]
Oh okay, I get it now. Makes sense honestly.
So literally /SteamPath should be used with Steam only.
And you want a new launch parameter that would run your wrapper instead of Steam.
I'll get on it. LaunchCommand seems a suitable name for it.

**Comment by lemasato** [comment]
/LaunchCommand="C:\Program Files (x86)\MySteamWrapper\app.exe"
I tested, should work just fine, including if wrapper has launch params.
Is this suitable to your need?

**Comment by Lucide** [comment]
Works perfectly

**Comment by lemasato** [comment]
Released as of [0.2.3](https://github.com/lemasato/Steam-Account-Switcher/releases/tag/0.2.3)
Thank you for the recommendation!
