### ISSUE TITLE
App redownloads itself when no update is available

### ISSUE THREAD

**Issue by MushuPorkPls** [lemasato/Steam-Account-Switcher#10]
Since the latest update the app seems to redownload itself as an 'update'  every time on launch

**Comment by lemasato** [comment]
Strange, tested and doesn't happen neither the AHK or the executable.
Are you using a shortcut, or did you rename the executable?
I know that when updating, the downloaded executable is being renamed back to the default "Steam Account Switcher".
And so, if for example you changed the executable name and you're using a shortcut, this would make you run the old version - which would then trigger the auto updating process.

**Comment by MushuPorkPls** [comment]
Thanks for the prompt response! I do have a shortcut pinned in the Start menu, and when i open the file location I can see two executables, "Steam-Account-Switcher.exe" and "Steam Account Switcher.exe", where the latter appears to be the newer version. My shortcut was indeed referencing the older version, as I was unaware of the rename. Updating the shortcut fixed the problem; thanks!
