### ISSUE TITLE
Endless Update Loop

### ISSUE THREAD

**Issue by eltoro0815** [lemasato/Steam-Account-Switcher#11]
Hi,

when i start version v.0.2.2 i see that the updater thinks there is a new version and downloads it. The current github version is 0.2.3. But after the update the version stays 0.2.2. So the update process starts again and again each time i start the program.

**Comment by eltoro0815** [comment]
I realized that the program exists 2x on my desktop. Version 0.2.2 and 0.2.3 parallel at the same time. Is this intended?

**Comment by lemasato** [comment]
I believe this is the same situation as here #10
