### ISSUE TITLE
Download Exception at every start

### ISSUE THREAD

**Issue by RainbowSimon** [lemasato/Steam-Account-Switcher#13]
So this is nothing too bad, becuase the app works just fine, just a little annoying.

This issue is that it seems to throw an exception on trying to update the app. Im sure you understand your program better than I do... 
Maybe anything with the request? Anyway, here's a screenshot of it.
![image](https://user-images.githubusercontent.com/38660607/105892368-0edd6400-6012-11eb-9388-11d199305ba9.png)

**Comment by eltoro0815** [comment]
Same issue every start here.

![image](https://user-images.githubusercontent.com/18168608/105917782-2547e780-6033-11eb-8aa1-91146f78d608.png)

**Comment by lemasato** [comment]
Fixed as of 0.2.4, thank you for the report!
No need to update manually, update checking still worked beside the error message. The next time the app checks for update, you will get this error box again but then you'll get the update prompt as usual.
