### ISSUE TITLE
False positives on multiple AVs?

### ISSUE THREAD

**Issue by throny** [lemasato/Steam-Account-Switcher#15]
I got problems while using the latest release getting reported as "Trojan:Win32/Azorult!ml" on Windows Defender. Uploaded it to Virustotal and got a 10/70.

Can you please check and maybe pack the exe on a different way?

**Comment by Yimura** [comment]
Can confirm I have this as well.

**Comment by lemasato** [comment]
#14 
Nothing can be done about it. It's a widespread issue among AHK compiled scripts. Stick to the AHK zip only, it works the same, no flagging issue as it's literally text files.
