### ISSUE TITLE
Failed to load steamui.dll

### ISSUE THREAD

**Issue by ThePixelGamer** [lemasato/Steam-Account-Switcher#4]
![image](https://user-images.githubusercontent.com/15077848/70114910-ab30f400-1623-11ea-8b41-b0e3c1389e7f.png)
Doesn't show up if I launch normally.

**Comment by lemasato** [comment]
Late answer by almost a year. Let me know if it still happens, and if so, in which case.
Also make sure you didn't mistake this project for another account switcher. Closing this to keep the issues tab clean in the meantime.
