### ISSUE TITLE
Issues with High DPI Scaling

### ISSUE THREAD

**Issue by lunim** [lemasato/Steam-Account-Switcher#9]
I'm running my display at 4k with 200% scaling.  The accounts/options and login buttons are all very tiny.

Also, it would be nice if the app offered a touch friendly mode, with bigger/spaced out user names.

**Comment by lemasato** [comment]
Fixed after over a month, sorry it took so long (especially that as you can see the changes are very small). Update is not pushed yet, waiting for a reply over another issue. This fix will be part of 0.2.3.
Thank you for reporting, and once again, I'm sorry.

**Comment by lunim** [comment]
@lemasato Hello, any update for on when this will be released?

**Comment by lemasato** [comment]
Right away, my bad.
